export const message = {
  TOKEN_EXPIRED: "Token expired. Please login again.",
  INVALID_TOKEN: "Invalid token",
  PASSWORD_MISMATCH: " Passwords do not match",
  INVALID_LOGIN: "Invalid email or password",
  UNAUTHORIZED: "Unauthorized, please login",
  LOGIN_SUCCESS: "Login successful",
  USER_CREATED: "User created",
  USER_NOT_FOUND: "User not found",
  CONFIRM_PASSWORD: "Confirm password",
  PASSWORD_NOT_MATCHING: "Password not matching",
  USER_EXISTS: "User already exists",
  WELCOME_EMAIL: "Contact information saved and welcome email sent",
  NO_FILE_UPLOADED: "No file uploaded",
  FAILED_TO_CREATE_BLOG: "Failed to create blog",
  BLOG_NOT_FOUND: "Blog not found",
  FAILED_TO_UPDATE_BLOG: "Failed to update blog",
  BLOG_CREATED: "Blog created",
  BLOG_DELETED: "Blog deleted successfully",
  FAILED_TO_DELETE_BLOG: "Failed to delete blog",
  BLOG_UPDATED: "Blog updated",
  FAILED_TO_RETRIEVE_BLOG: "Failed to retrieve blog' ",
  FAILED_TO_CREATE_TESTIMONIAL: "Failed to create testimonial",
  TESTIMONIAL_NOT_FOUND: "Testimonial not found",
  FAILED_TO_UPDATE_TESTIMONIAL: "Failed to update testimonial",
  TESTIMONIAL_DELETED: "Testimonial deleted successfully",
  FAILED_TO_DELETE_TESTIMONIAL: "Failed to delete testimonial",
  FAILED_TO_RETRIEVE_TESTIMONIAL: "Failed to retrieve testimonial",
  TESTIMONIAL_CREATED_SUCCESS: "Testimonial created successfully",
  TESTIMONIAL_UPDATED_SUCCESS: "Testimonial updated successfully",
  INVALID_FILE_TYPE: "Invalid file type",
  PAGE_CREATED: "Page created",
  FAILED_TO_CREATE_PAGE: "Failed to create page",
  PAGE_NOT_FOUND: "Page not found",
  PAGE_UPDATED: "Page updatd",
  FAILED_TO_UPDATE_PAGE: "Failed to update page",
  PAGE_DELETED: "Page deleted",
  FAILED_TO_DELETE_PAGE: "Failed to delete page",
  FAILED_TO_RETRIEVE_PAGE: "Failed to retrieve page",
  UNIQUE_PAGE: " A page with the same URL or name already exists.",
  GALLERY_ITEM_NOT_FOUND: "Gallery item not found",
  FILE_NOT_FOUND: "File not found",
  FAILED_TO_UPDATE_FILE: "Failed to upload file",
  FILE_DELETED_SUCCESSFULT: "File deleted successfully",
  VIDEO_URL_NOT_PROVIDED: "Video url not provided",
  FAILED_TO_UPLOAD_FILE: "Failed to upload file",
  FAILED_TO_SEND_FILE: "Failed to send the file.",
  FAIL_NOT_FOUND_ON_SERVER: "File not found on server",
  COMMENT_CREATED: "Comment created",
  FAILED_TO_GET_COMMENTS_BY_BLOGID: "Failed to get comments by blogId",
  FAILED_TO_GET_COMMENTS_BY_ID: "Failed to get comments by id",
  COMMENT_NOT_FOUND: "Comment not found",
  FAILED_TO_GET_ALL_COMMENTS: "Failed to get all comments",
  COMMENT_DELETED_SUCCESSFULLY: "Comment deleted successfully",
  COMMENT_UPDATED: "Comment updated",
  PAGE_STATUS_UPDATED: "Page status updated",
  TESTIMONIAL_STATUS_UPDATED: "Testimonial status updated",
  SERVICE_CREATED: "Service created",
  UNIQUE_SERVICE: "Unique service",
  SERVICE_NOT_FOUND: "Service not found",
  SERVICE_UPDATED: "Service updated",
  SERVICE_DELETED: "Service deleted",
  FAILED_TO_RETRIEVE_SERVICE: "Failed to retrieve service",
  SERVICE_STATUS_UPDATED: "Service status updated",
  CATEGORY_UPDATED_SUCCESS: "Category updated",
  CATEGORY_ALREADY_EXISTS: "Category already exists",
  CATEGORY_CREATED_SUCCESS: "Category created",
  FAILED_TO_RETRIEVE_CATEGORY: "Failed to retrieve category",
  CATEGORY_STATUS_UPDATED: "Category status updated",
  CATEGORY_NOT_FOUND: "Category not found",
  CATEGORY_DELETED: "Category deleted",
  BLOG_STATUS_UPDATED: "Blog status updated",
  FAILED_TO_CREATE_CATEGORY: "Failed to create category",
  GALLERY_CREATED: "Gallery created",
  FAILED_TO_ADD_GALLERY: "Failed to add gallery",
  GALLERY_NOT_FOUND: "Gallery not found",
  GALLERY_UPDATED: "Gallery updated",
  GALLERY_DELETED: "Gallery deleted",
  FAILED_TO_RETRIEVE_GALLERIES: "Failed to retrieve gallery",
  GALLERY_STATUS_UPDATED: "Gallery status updated",
  WEBSITE_SETTINGS_CREATED_SUCCESS: "Website settings created",
  WEBSITE_SETTINGS_NOT_FOUND: "Website settings not found",
  WEBSITE_SETTINGS_UPDATED_SUCCESS: "Website settings updates successfully",
  WEBSITE_SETTINGS_DELETED: "Website settings deleted",
  FAILED_TO_RETRIEVE_WEBSITE_SETTINGS: "Failed to retrieve website settings",
  WEBSITE_SETTINGS_STATUS_UPDATED: "Website settings status updated",
  ALREADY_WEBSITE_SETTINGS_EXISTS: "Already website settings exists",
  PORTFOLIO_NOT_FOUND: "Portfolio not found",
  PORTFOLIO_STATUS_UPDATED: "Portfolio status updated",
  FAILED_TO_RETRIEVE_PORTFOLIOS: "Failed to retrieve portfolios",
  PORTFOLIO_DELETED: "Portfolio deleted",
  PORTFOLIO_UPDATED_SUCCESS: "Portfolio updated succesfully",
  PORTFOLIO_CREATED_SUCCESS: "Portfolio created success",
};
