name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up commit SHA variable
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --tag ghcr.io/minute-designs-team/minutedesigns-website-backend:${{ env.SHORT_SHA }} \
            --tag ghcr.io/minute-designs-team/minutedesigns-website-backend:latest

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: minute-suchithrashiju
          password: ${{ secrets.GH_TOKEN }}

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/minute-designs-team/minutedesigns-website-backend:${{ env.SHORT_SHA }}
          docker push ghcr.io/minute-designs-team/minutedesigns-website-backend:latest
